rm(list=ls())
library(xml2)
url <- "https://en.wikipedia.org/wiki/Web_scraping"
# rl <- readLines(url)
rh <- read_html(url)
### xml_children() vs xml_child()
xml_children(rh)
xml_child(rh, 2)
xml_children(rh)[2]
xml_length(xml_child(rh, 2))
xml_length(xml_children(rh)[2])
xml_children(xml_child(rh, 2))
xml_children(xml_children(rh)[2])
xml_child(xml_child(rh, 2), 1)
xml_children(xml_children(rh)[2])[1]
length(as_list(xml_child(rh, 2)))
length(as_list(xml_children(rh)[2]))
### tree structure & xml_length()
xml_length(rh)
xml_children(rh)
xml_length(xml_children(rh))
xml_length(xml_children(rh)[2])
xml_children(xml_children(rh)[2])
xml_length(xml_children(xml_children(rh)[2]))
xml_length(xml_children(xml_children(rh)[2])[3])
xml_children(xml_children(xml_children(rh)[2])[3])
xml_length(xml_children(xml_children(xml_children(rh)[2])[3]))
xml_length(xml_children(xml_children(xml_children(rh)[2])[3])[5])
xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])
xml_length(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5]))
xml_length(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])
xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])
xml_length(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7]))
xml_length(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])[2])
xml_children(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])[2])
xml_length(xml_children(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])[2]))
### xml_parents() & xml_siblings()
xml_parents(rh)
xml_parent(rh)
xml_parents(xml_children(xml_children(xml_children(rh)[2])[3]))
xml_parent(xml_children(xml_children(xml_children(rh)[2])[3]))
xml_children(xml_children(xml_children(rh)[2])[3])
xml_children(xml_children(xml_children(rh)[2])[3])[1]
xml_siblings(xml_children(xml_children(xml_children(rh)[2])[3])[1])
