rm(list=ls())
library(xml2)
url <- "https://en.wikipedia.org/wiki/Web_scraping"
# rl <- readLines(url)
rh <- read_html(url)
### xml_children() vs xml_child()
xml_children(rh)
xml_child(rh, 2)
xml_children(rh)[2]
xml_length(xml_child(rh, 2))
xml_length(xml_children(rh)[2])
xml_children(xml_child(rh, 2))
xml_children(xml_children(rh)[2])
xml_child(xml_child(rh, 2), 1)
xml_children(xml_children(rh)[2])[1]
length(as_list(xml_child(rh, 2)))
length(as_list(xml_children(rh)[2]))
### tree structure & xml_length()
xml_length(rh)
xml_children(rh)
xml_length(xml_children(rh))
xml_length(xml_children(rh)[2])
xml_children(xml_children(rh)[2])
xml_length(xml_children(xml_children(rh)[2]))
xml_length(xml_children(xml_children(rh)[2])[3])
xml_children(xml_children(xml_children(rh)[2])[3])
xml_length(xml_children(xml_children(xml_children(rh)[2])[3]))
xml_length(xml_children(xml_children(xml_children(rh)[2])[3])[5])
xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])
xml_length(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5]))
xml_length(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])
xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])
xml_length(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7]))
xml_length(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])[2])
xml_children(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])[2])
xml_length(xml_children(xml_children(xml_children(xml_children(xml_children(xml_children(rh)[2])[3])[5])[7])[2]))
### xml_parents() & xml_siblings()
xml_parents(rh)
xml_parent(rh)
xml_parents(xml_children(xml_children(xml_children(rh)[2])[3]))
xml_parent(xml_children(xml_children(xml_children(rh)[2])[3]))
xml_children(xml_children(xml_children(rh)[2])[3])
xml_children(xml_children(xml_children(rh)[2])[3])[1]
xml_siblings(xml_children(xml_children(xml_children(rh)[2])[3])[1])
### xml_contents()
xml_contents(xml_children(rh)[2])
xml_children(xml_children(rh)[2])
### html_structure()
xml_children(xml_children(rh)[1])
html_structure(xml_children(rh)[1])
### xml_find_all(), xml_find_first(), xml_path(), xml_attrs(), xml_pat(), xml_text()
# //  finds anywhere in the document (ignoring the current node)
# .// finds anywhere beneath the current node
xml_find_all(rh, ".//div")[1:10]
xml_path(xml_find_all(rh, ".//div")[1:10])
xml_find_all(xml_find_all(rh, ".//div")[1:5], ".//div")
xml_find_all(xml_find_all(rh, ".//div")[1:5], "//div")
xml_find_first(rh, ".//div")
xml_attrs(xml_find_all(rh, ".//div")[1:10])
xml_attr(xml_find_all(rh, ".//div")[1:10], "id")
xml_attr(xml_find_all(rh, ".//div")[1:10], "class")
xml_contents(xml_find_all(rh, "//b")[1:10])
xml_path(xml_children(xml_children(rh)[1])[3])
xml_text(xml_find_all(rh, ".//div")[3])